// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20240610232830_AddLastUpdateToFlightSearch")]
    partial class AddLastUpdateToFlightSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.FlightOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("FlightSearchKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Itineraries")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfBookableSeats")
                        .HasColumnType("int");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FlightSearchKey");

                    b.ToTable("FlightOffers");
                });

            modelBuilder.Entity("Entities.FlightSearch", b =>
                {
                    b.Property<string>("SearchKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("SearchKey");

                    b.ToTable("FlightSearches");
                });

            modelBuilder.Entity("Entities.FlightOffer", b =>
                {
                    b.HasOne("Entities.FlightSearch", "FlightSearch")
                        .WithMany("FlightOffers")
                        .HasForeignKey("FlightSearchKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightSearch");
                });

            modelBuilder.Entity("Entities.FlightSearch", b =>
                {
                    b.Navigation("FlightOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
